### ISSUE TITLE
Lack of the document of id_seq_right.json

### ISSUE THREAD

**Issue by Doreeeeen** [AlanJiang98/EvRGBHand#1]
I get an error when I execute the command "python train.py --config src/configs/config/evrgbhand.yaml --resume_checkpoint output/EvImHandNet.pth --config_merge src/configs/config/eval_temporal.yaml --run_eval_only --output_dir result/evrgbhand/"

FileNotFoundError: [Errno 2] No such file or directory: '/home/jd/miniconda3/EvRGBHand-main/src/datasets/id_seq_right.json'

How do I get this file?

**Comment by AlanJiang98** [comment]
This file is part of our dataset. We are reorganizing our dataset and will release it soon.

**Comment by Doreeeeen** [comment]
Thanks!
