### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by jkpark08** [AlanJiang98/EvRGBHand#2]
Thank you for the great work.
Could I know when the dataset will be released?

**Comment by AlanJiang98** [comment]
Thank you for your reminder. [Our dataset](https://www.dropbox.com/scl/fi/x3bmfw2tfmqaghagb6alx/EvRealHands.zip) is available here. Additionally, we have updated the README to facilitate a clearer understanding of our work.

**Comment by jkpark08** [comment]
Thank you for the prompt response!

Also, how do you obtain 2D keypoints in blurry hand images? Sometimes their behavior seems unpredictable.

**Comment by AlanJiang98** [comment]
Yes, labeling on blurred RGB images is challenging. Here, we annotate on the 2D representation of the event stream (as event streams do not experience blur issues). After getting predicted 3D keypoints, we project these 3D keypoints onto the imaging plane of the event camera to compare and calculate metrics such as 2D-MPJPE. 

Another method is to increase the camera exposure time to induce image blur, while keeping the exposure time of other cameras constant. From the 2D annotations of other cameras, we calculate the final 3D keypoints and project them onto the imaging plane of the camera that experienced blur.

**Comment by jkpark08** [comment]
Great thank you for the response!

**Comment by jkpark08** [comment]
Close the issue, as solved.
