### ISSUE TITLE
Data Crop

### ISSUE THREAD

**Issue by rwn17** [AlanJiang98/EvRGBHand#3]
Hi @AlanJiang98 ,

Thanks for your excellent work! It's truly amazing!

I noticed that the data for the network input is a cropped image in a 192x192 rectangle. I'm curious, how exactly is this crop generated? Is it based on hand annotation or is it machine-generated?

Best regards,
Weining

**Comment by AlanJiang98** [comment]
Hand annotation.
As you can see in https://github.com/AlanJiang98/EvRGBHand/blob/main/src/datasets/EvRealHands.py#L554 and https://github.com/AlanJiang98/EvRGBHand/blob/main/src/datasets/EvRealHands.py#L538 , we use the 3d joints to project them on the image plane to get a brief cropped image.

In practical applications, the complete process involves the machine detecting the bboxes and then predicting the 3D hand mesh based on bboxes. In our task, we focus more on the latter stage. Additionally, some tests in datasets like InterHand2.6M and FreiHand are also set up this way.

**Comment by rwn17** [comment]
Aha, impressive. I'm new to this field, so it seems to be a tradition in hand pose estimation. Thanks for your prompt reply. I will close this issue.
